### ISSUE TITLE
Gaps in skinned meshes along uv seams

### ISSUE THREAD

**Issue by FeuerTiger86** [Greatness7/io_scene_mw#9]
While working on my latest mods, Detailed Daedroth and Amazing Atronachs, I encountered this problem twice: Exporting skinned meshes sometimes results in gaps in the model that are only visible ingame, not in Blender and not in NifSkope. It looks like they are always appearing along seams in the uv map, but not along all seams. For example, in the flame atronach, the seam runs vertically over the entire back, but there was only a small gap visible on the neck.

Apparently it has to do with with how many weights per vertex there are. It seems that three is the maximum that works. Even then, some vertices behave a little differently than they do in Blender or NifSkope, but not too dramatically. Also, it looks like a gap can already appear if adjacent vertices have four or more weights. But I'm not entirely sure about that.

Greetings and keep up the great work,
Pherim

**Comment by Greatness7** [comment]
What you're seeing is a limitation of the Morrowind engine. (Hence why it's not visible in other renderers like Blender/Nifskope/OpenMW)

Essentially skinning in Morrowind is limited to a maximum of 4 bone influences per drawable (aka per `NiTriShape`). When a shape has more than four bone influences the engine will "partition" it into separate chunks to stay within that limit.

The partitioning process basically boils down to going through each triangle and taking the top 4 most significant bone influences, discarding the rest, then splitting off the groups that share bones into separate shapes.

Since partitioning is a lossy process (some bone influences are discarded) it can end up causing skinning artifacts in the final render. Most often are the seams where two triangles that share an edge ended up in different partitions and thus now have different bone weights influencing them.

Unfortunately the only truly reliable way to avoid this is to limit yourself to 4 bones per shape, splitting things up manually when necessary. Besides that your best bet is to just use as few bones influences as you can manage and hope the partitioning process produces a good result. Blender's automatic weighting algorithms unfortunately tend to do the reverse and use a lot more bones than necessary. The `Limit Total Vertex Groups` and `Limit Number of Weights per Vertex` operators can be useful to mitigate that.

**Comment by FeuerTiger86** [comment]
That's good to know, thank you for this information!
